### ISSUE TITLE
Bot not adding words

### ISSUE THREAD

**Issue by GoByeBye** [bozoweed/Bot-s0urce.io#3]
Yeah so whenever the bot tries to solve the words it finds it but it ends up with [Undefined] if you want the code here 

:: . Now attacking 66	Anon357
VM1313:400 :: . Handling upgrades to firewall 3
VM1313:400 :: . Charge isn't maxed
VM1313:400 :: . Regen isn't maxed
VM1313:400 :: . Found word: [http://s0urce.io/client/img/word/e/16]
VM1313:400 :: .[undefined]
VM1313:400 :: * Not seen, trying OCR...
VM1313:400 :: * OCR failed
VM1313:400 :: * Stopped loops
VM1313:400 :: . Now attacking 65	Anon294
VM1313:400 :: . Handling upgrades to firewall 1
VM1313:400 :: . Charge isn't maxed
VM1313:400 :: . Regen isn't maxed
VM1313:400 :: . Found word: [http://s0urce.io/client/img/word/e/48]
VM1313:400 :: .[undefined]
VM1313:400 :: * Not seen, trying OCR...
VM1313:400 :: * OCR failed
VM1313:400 :: * Stopped loops
VM1313:400 :: . Now attacking 65	Anon294
VM1313:400 :: . Handling upgrades to firewall 2
VM1313:400 :: . Charge isn't maxed
VM1313:400 :: . Regen isn't maxed
VM1313:400 :: . Found word: [http://s0urce.io/client/img/word/e/16]
VM1313:400 :: .[undefined]
VM1313:400 :: * Not seen, trying OCR...
VM1313:400 :: * OCR failed
VM1313:400 :: * Stopped loops

**Comment by cacareco** [comment]
it's because the word image file url changed, just need to get a new updated database with the correct links... it might take a while to get all of the links

**Comment by cacareco** [comment]
http://s0urce.io/client/img/word/h/34
http://s0urce.io/client/img/word/h/33
http://s0urce.io/client/img/word/h/32
http://s0urce.io/client/img/word/e/20

**Comment by bozoweed** [comment]
Fixed
